---
- name: Deploy NSX Infra on AWS
  hosts: localhost
  connection: local
  gather_facts: True
  vars_files:
    - ./answerfile.yml
  tasks:
    - name: Set the Key location as fact 
      set_fact: 
        ssh_key_location: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"

    - name: "Check that the SSH Key exists for {{ ansible_env.USER }} user"
      stat:
        path: "{{ ssh_key_location }}"
      register: sshkey_result

    - name: "Generating a new SSH key for {{ ansible_env.USER }} user if does not already exists"
      user:
        name: "{{ ansible_env.USER }}"
        generate_ssh_key: yes 
        ssh_key_bits: 2048
      when: sshkey_result.stat.exists == False

    - name: Creates an new ec2 key with mentioned name if not present
      ec2_key:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ mng_vpc_region }}"
        name: "nsxman-key"
        state: present
        key_material:  "{{ lookup('file',  ssh_key_location ) }}"

- name: Deploy NSX Infra on AWS
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - ./answerfile.yml
  tasks:
    - name: Create Management Security Group
      ec2_group:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ mng_vpc_region }}"
        vpc_id: vpc-bdbc89da  # EDIT
        name: ManagementSecGroup
        description: Security Group for NSX Management Components
        rules: "{{ ManagementSecGroup.rules }}"
        state: present
      register: mngmtsg
    - name: Tag the Management Security Groups
      ec2_tag:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ mng_vpc_region }}"
        resource: "{{ mngmtsg.group_id }}"
        state: present
        tags:
          Name: "ManagementSecGroup"
          Project: "{{ project }}"
          Student: "{{ student }}"
    - name: Get NSX Manager AMI ID
      ec2_ami_find:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ mng_vpc_region }}"
        name: "nsx-manager-*"
        sort: name
        sort_order: descending
        sort_end: 1
        no_result_action: fail
        state: available
      register: nsxmanami
    - name: Launch NSX Manager instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ mng_vpc_region }}"
        image: "{{ nsxmanami.results[0].ami_id }}"
        instance_type: m3.large
        key_name: nsxman-key
        wait: yes
        vpc_subnet_id: subnet-8e1b5be9  # EDIT
        assign_public_ip: yes
        instance_tags:
          Name: "NSX Manager"
          Project: "{{ project }}"
          Student: "{{ student }}"
        exact_count: 1
        count_tag:
          Name: "NSX Manager"
          Project: "{{ project }}"
          Student: "{{ student }}"
        group_id: "{{ mngmtsg.group_id }}"
      register: nsxmaninstance
    - name: Remove previous SSH keys from known_hosts - Manager
      command: 'ssh-keygen -R "{{ nsxmaninstance.instances[0].public_ip }}"'
      register: command_result
      failed_when: "command_result.rc > 0 and command_result.rc != 255"
    - name: Wait for SSH to come up on NSX Manager
      wait_for:
        host: "{{ nsxmaninstance.instances[0].public_ip }}"
        port: 22
        search_regex: OpenSSH
        delay: 15
    - name: add host to known_hosts - Manager
      shell: 'ssh-keyscan -H "{{ nsxmaninstance.instances[0].public_ip }}" >> ~/.ssh/known_hosts'
