---
- name: Read in AWS Access Key and Secret Key from .aws/credentials file
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Read access and secret keys
      set_fact:
        aws_access_key: "{{ lookup('ini', 'aws_access_key_id section={{ aws_credentials_profile }} file=~/.aws/credentials') }}"
        aws_secret_key: "{{ lookup('ini', 'aws_secret_access_key section={{ aws_credentials_profile }} file=~/.aws/credentials') }}"
      when: (aws_access_key == False and aws_secret_key == False)