---
- name: Configure NSX
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Set NSX Admin Password to Manager
      command: 'ssh admin@"{{ nsxmaninstance.instances[0].public_ip }}" set user admin password "{{ nsx_admin_password }}" old-password VMware!mgr1998'
      when: nsx_admin_password != "VMware!mgr1998"
      register: nsxadminpass

    - name: Set NSX Admin Password to CSM
      command: 'ssh admin@"{{ nsxcsminstance.instances[0].public_ip }}" set user admin password "{{ nsx_admin_password }}" old-password VMware!mgr1998'
      when: nsx_admin_password != "VMware!mgr1998"
      register: nsxadminpasscsm

    - name: Retrieve thumbprint
      command: 'ssh admin@"{{ nsxmaninstance.instances[0].public_ip }}" get certificate api thumbprint'
      register: thumbprint
    - name: Join controller to Manager
      command: 'ssh admin@"{{ nsxctrinstance.instances[0].public_ip }}" join management-plane "{{ nsxmaninstance.instances[0].private_ip }}" username admin password "{{ nsx_admin_password }}" thumbprint "{{ thumbprint.stdout }}" '
      ignore_errors: True
      register: ctrjoin
      until: ctrjoin.stdout == "Node successfully registered and controller restarted"
      retries: 3
      delay: 60
    - name: Set control cluster shared secret
      command: 'ssh admin@"{{ nsxctrinstance.instances[0].public_ip }}" set control-cluster security-model shared-secret secret VMware1! '
      register: ctrsecret
    - name: Initialize the controller cluster
      command: 'ssh admin@"{{ nsxctrinstance.instances[0].public_ip }}" initialize control-cluster '
      register: ctrinit
      until: ctrinit.stdout == "Control cluster initialization successful."
      retries: 3
      delay: 90
    - name: Activate the controller
      command: 'ssh admin@"{{ nsxctrinstance.instances[0].public_ip }}" activate control-cluster '
      register: ctract
      until: ctract.stdout == "Control cluster activation successful."
      retries: 3
      delay: 60








